/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const RecipesLazyImport = createFileRoute('/recipes')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RecipesLazyRoute = RecipesLazyImport.update({
  path: '/recipes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/recipes.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/recipes': typeof RecipesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/recipes': typeof RecipesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/recipes': typeof RecipesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes'
  id: '__root__' | '/' | '/recipes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RecipesLazyRoute: typeof RecipesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RecipesLazyRoute: RecipesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipes"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/recipes": {
      "filePath": "recipes.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
