/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as RecipesSlugImport } from './routes/recipes/$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesSlugRoute = RecipesSlugImport.update({
  path: '/recipes/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/recipes/': typeof RecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes/$slug' | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes/$slug' | '/recipes'
  id: '__root__' | '/' | '/recipes/$slug' | '/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesSlugRoute: RecipesSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipes/$slug",
        "/recipes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/recipes/$slug": {
      "filePath": "recipes/$slug.tsx"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
